spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
#              memory: 256Mi
            limits:
              cpu: "1.0"
#              memory: 256Mi
        - volumeMounts:
          - name: vol03
            mountPath: /deployments
      volumes:
        - name: vol03
          persistentVolumeClaim:
           claimName: pvc03 
